export {Nav} from './Nav'
export {Main} from './Main'
export {Presentation} from './Presentation'
export {Layout} from './Layout'
export {ProfileCard} from './Profile-card'
export {FunFacts} from './Fun-facts'
export {Footer} from './Footer'